#!/bin/bash

help_text=$(<help.txt) # Read the help from a file

if [ "$1" == "--help" ]
then
    echo
    echo "$help_text" # This is in quotes to allow for line breaks
    echo
    exit 0
fi

# This is just a big ol' switch statement
while [ $# -ne 0 ]
do
    case "$1" in
        ########## Do all the options
        'all')
            ##### Files

            cp .vimrc ~
            cp .bash_aliases ~ && source ~/.bash_aliases
            cp .bashrc ~ && source ~/.bashrc
            cp .gitconfig ~
            cp .tern-config ~

            neofetch --version
            if [[ $? -ne 0 ]]
            then
                sudo apt install -y neofetch
            fi

            cp neofetch_config ~/.config/neofetch/config.conf

            ##### Plugins

            # Check if curl is installed
            curl --version
            # If curl is not installed the exit code will not be 0, so we should install it
            if [[ $? -ne 0 ]]
            then
                sudo apt -y install curl
            fi
            # Install vim-plug in autoload directory
            curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

            # Clone github repo for Vundle into proper directory
            git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

            vim -c "PlugInstall" -c "qa!"
            vim -c "PlugUpdate" -c "qa!"

            vim -c "PluginInstall" -c "qa!"
            vim -c "PluginUpdate" -c "qa!"

            sudo apt -y install build-essential cmake vim-nox python3-dev
            sudo apt -y install mono-complete golang nodejs default-jdk npm
            python3 ~/.vim/bundle/YouCompleteMe/install.py --all
            exit
        ;;

        ########## Files
        'vimrc')
            cp .vimrc ~
            shift
            continue
        ;;

        'bash-aliases')
            cp .bash_aliases ~ && source ~/.bash_aliases
            shift
            continue
        ;;

        'bashrc')
            cp .bashrc ~ && source ~/.bashrc
            shift
            continue
        ;;

        'gitconfig')
            cp .gitconfig ~
            shift
            continue
        ;;

        'tern-config')
            cp .tern-config ~
            shift
            continue
        ;;

        'install-neofetch')
            neofetch --version
            if [[ $? -ne 0 ]]
            then
                sudo apt install -y neofetch
            fi
            shift
            continue
        ;;

        'neofetch-config')
            cp neofetch_config ~/.config/neofetch/config.conf
            shift
            continue
        ;;

        ########## Plugins
        'install-vim-plug')
            # Check if curl is installed
            curl --version
            # If curl is not installed the exit code will not be 0, so we should install it
            if [[ $? -ne 0 ]]
            then
                sudo apt -y install curl
            fi
            # Install vim-plug in autoload directory
            curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            shift
            continue
        ;;

        'install-vundle')
            # Clone github repo for Vundle into proper directory
            git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
            shift
            continue
        ;;

        'install-vim-plug-plugins')
            vim -c "PlugInstall" -c "qa!"
            vim -c "PlugUpdate" -c "qa!"
            shift
            continue
        ;;

        'install-ycm-depend')
            sudo apt -y install build-essential cmake vim-nox python3-dev
            sudo apt -y install mono-complete golang nodejs default-jdk npm
            python3 ~/.vim/bundle/YouCompleteMe/install.py --all
            shift
            continue
        ;;

        'install-vundle-plugins')
            vim -c "PluginInstall" -c "qa!"
            vim -c "PluginUpdate" -c "qa!"
            shift
            continue
        ;;

        *)
            echo "auto-setup must be supplied with an argument. See --help to see all options."
            exit 1
        ;;

    esac
done
