#!/usr/bin/env bash

DIR="/tmp/compiledir"
mkdir -p $DIR

_install_python() {
	cd $DIR

	wget https://www.python.org/ftp/python/$1/Python-$1.tgz
	tar xzvf Python-$1.tgz
	cd Python-$1/

	./configure --prefix=/home/dyson/.local --enable-optimizations --enable-shared
	make && make test && make altinstall

	cd $DIR
	rm -rf Python-$1*
}

install_python38() {
	_install_python 3.8.13
}

install_python39() {
	_install_python 3.9.13
}

install_python310() {
	_install_python 3.10.6
}

while [ $# -ne 0 ]; do
	case "$1" in
		'all')
			install_python38
			install_python39
			install_python310
			exit 0
		;;

		'python')
			install_python38
			install_python39
			install_python310
			shift
			continue
		;;
	esac
done

rm -rf $DIR
