#!/bin/bash

# Regex to check user input
yn_regex='^[Yy].*'

# Function to optionally copy a file (takes two arguments - the file to copy, and the directory to copy it to; returns 0 if successful, 1 if unsuccessful, and 2 if not copied)
OptionalCopy() {
    echo # Create a blank line to pad things out a bit
    read -p "Would you like to copy $1 to your home directory? (Y/n) " copy_var

    if [[ $copy_var =~ $yn_regex ]]
    then
        cp $1 $2 && echo "$1 copied";return 0 || echo "$1 failed to copy";return 1
    else
        echo "$1 not copied";return 2
    fi
}

OptionalCopyAndSource () {
    # I just copied the whole OptionalCopy function in here (with minor alterations) because calling the function didn't seem to work
    echo # Create a blank line to pad things out a bit
    read -p "Would you like to copy $1 to your home directory? (Y/n) " copy_var

    if [[ $copy_var =~ $yn_regex ]]
    then
        cp $1 $2 && echo "$1 copied";source_var=true || echo "$1 failed to copy";success_var=false
    else
        echo "$1 not copied";source_var=false
    fi

    if $source_var ; then
        source $2/$1 && echo "$1 sourced" || echo "$1 failed to source"
    fi
}

########## USER INTERACTION ##########

# Warn the user before doing anything
echo "NOTE: This setup utility was designed primarily for Ubuntu and will not work on distros without apt installed"
echo
echo "WARNING: This script has options to overwrite important files and install lots of stuff, which will take time and bandwidth."
read -p "Would you like to continue? (Y/n) " continue_var

if [[ ! $continue_var =~ $yn_regex ]] # If not continue, quit script
then
    exit 0 # Exit successfully
fi

echo
echo "========== FILE MOVEMENT =========="
echo

read -p "Would you like to move any files to your home directory? (Y/n) " file_move_var

if [[ $file_move_var =~ $yn_regex ]]
then
    OptionalCopy .vimrc ~

    OptionalCopyAndSource .bash_aliases ~

    OptionalCopyAndSource .bashrc ~

    OptionalCopy .gitconfig ~

    OptionalCopy .tern-config ~

    OptionalCopy neofetch_config ~/.config/neofetch/config.conf
fi

echo
echo "========== VIM PLUGINS =========="
echo
read -p "Would you like to install any vim plugins or their managers? (Y/n) " vim_plugins_var

if [[ $vim_plugins_var =~ $yn_regex ]]
then
    echo
    echo "NOTE: If you don't install vim-plug and Vundle, vim will fail to load properly. Only decline these installations if they are already installed."
    echo

    read -p "Would you like to install vim-plug? (curl will also be installed if it's not already) (Y/n) " vim_plug_var

    if [[ $vim_plug_var =~ $yn_regex ]]
    then
        # Check if curl is installed
        curl --version

        # If curl is not installed the exit code will not be 0, so we should install it
        if [[ $? -ne 0 ]]
        then
            echo
            echo "curl is not installed. Installing it now..."
            echo
            sudo apt -y install curl
        fi

        # Install vim-plug in autoload directory
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
    echo

    read -p "Would you like to install Vundle? (Y/n) " vundle_var

    if [[ $vundle_var =~ $yn_regex ]]
    then
        # Clone github repo for Vundle into proper directory
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    fi
    echo

    read -p "Would you like to install and update all vim-plug plugins? (Y/n) " vim_plug_install_var

    if [[ $vim_plug_install_var =~ $yn_regex ]]
    then
        vim -c "PlugInstall" -c "qa!"
        vim -c "PlugUpdate" -c "qa!"
    fi
    echo

    read -p "Would you like to install all depenedencies for the YouCompleteMe plugin (this will take a long time)? (Y/n) " ycm_var

    if [[ $ycm_var =~ $yn_regex ]]
    then
        sudo apt -y install build-essential cmake vim-nox python3-dev
        sudo apt -y install mono-complete golang nodejs default-jdk npm
        python3 ~/.vim/bundle/YouCompleteMe/install.py --all
    fi
    echo

    read -p "Would you like to install and update all Vundle plugins? (Y/n) " vundle_install_var

    if [[ $vundle_install_var =~ $yn_regex ]]
    then
        vim -c "PluginInstall" -c "qa!"
        vim -c "PluginUpdate" -c "qa!"
    fi
fi

echo
echo "Thanks for using this setup utility!"
read -n 1 -s -r -p "Press any key to exit..."
echo
